---
- name: Create Proxmox VMs
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./group_vars/all/vault.yml 
  vars:
    proxmox_host: "192.168.1.100"  # your proxmox host ip
    proxmox_user: "ansible@pve"  # the Proxmox API user you created
    #
    # You will need to make an ansible vault file in this directory with the entry:
    # vault_proxmox_password: "your-password-here"
    #
    proxmox_password: "{{ vault_proxmox_password }}" 
    proxmox_node: "pve"  # rename according to your node name
    template_name: "rhel-9.6-template" # The name of the template you will be cloning

    # SSH credentials for the VMs (add these)
    vm_ssh_user: "ansible"  # The name of user you created on the template VM
    vm_ssh_password: "{{ vault_vm_ssh_password }}" 

    # Customization variables
    vm_base_name: "rhel-clone" # Base name for VMs
    vm_count: 1 # Number of VMs to create
    vm_memory: 4096 # Memory in MB
    vm_cores: 2 # CPU cores  

  tasks:
  - name: Get list of existing VMs
    community.proxmox.proxmox_vm_info:
      api_host: "{{ proxmox_host }}"
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      validate_certs: no
      node: "{{ proxmox_node }}"
    register: vm_list  # Store the list of VMs 

  - name: Calculate starting VMID # Find the maximum VM id in your proxmox node and add one for the starting VM id
    set_fact:
      starting_vmid: "{{ (vm_list.proxmox_vms | map(attribute='vmid') | map('int') | max | default(99)) + 1 }}"
      

  - name: Display starting VMID
    debug:
      msg: "Starting VMID: {{ starting_vmid }}, creating {{ vm_count }} VMs"

  - name: Clone VMs from template  # Make a number of clones of the vm
    community.proxmox.proxmox_kvm:
      api_host: "{{ proxmox_host }}"
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      validate_certs: no
      node: "{{ proxmox_node }}"
      clone: "{{ template_name }}"
      newid: "{{ starting_vmid | int + item }}"
      name: "{{ vm_base_name }}-{{ item + 1 }}" 
      full: yes
      timeout: 300
      memory: "{{ vm_memory }}"
      cores: "{{ vm_cores }}"
      state: present
    loop: "{{ range(0, vm_count) | list }}"
    register: cloned_vms

  - name: Start VMs
    community.proxmox.proxmox_kvm:
      api_host: "{{ proxmox_host }}"
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      validate_certs: no
      node: "{{ proxmox_node }}"
      vmid: "{{ starting_vmid | int + item }}"
      state: started
      timeout: 60
    loop: "{{ range(0, vm_count) | list }}"
    when: auto_start
  
  - name: Get VM network information
    community.proxmox.proxmox_vm_info:
      api_host: "{{ proxmox_host }}"
      api_user: "{{ proxmox_user }}"
      api_password: "{{ proxmox_password }}"
      validate_certs: no
      node: "{{ proxmox_node }}"
      vmid: "{{ starting_vmid | int + item }}"
      network: true
    loop: "{{ range(0, vm_count) | list }}"
    register: vm_info
    retries: 15
    delay: 3
    until: >
      vm_info.proxmox_vms[0].network is defined and
      vm_info.proxmox_vms[0].network | length > 0 and
      vm_info.proxmox_vms[0].network | selectattr('name', 'equalto', 'ens18') | list | length > 0 and
      (vm_info.proxmox_vms[0].network | selectattr('name', 'equalto', 'ens18') | first)['ip-addresses'] is defined

  - name: Extract VM IPs
    set_fact:
      vm_ips: >-
        {{ vm_ips | default([]) + 
          [(item.proxmox_vms[0].network 
            | selectattr('name', 'equalto', 'ens18') 
            | first)['ip-addresses'] 
            | selectattr('ip-address-type', 'equalto', 'ipv4') 
            | map(attribute='ip-address') 
            | first] }}
    loop: "{{ vm_info.results }}"
    when: >
      item.proxmox_vms[0].network is defined and
      item.proxmox_vms[0].network | selectattr('name', 'equalto', 'ens18') | list | length > 0 and
      (item.proxmox_vms[0].network | selectattr('name', 'equalto', 'ens18') | first)['ip-addresses'] is defined
    # this is ensuring that the network data structure exists, that at least one interface is present, uses network
    # interface ens18, and get IP if it has addresses assigned

  - name: Display collected IPs
    debug:
      msg: "VM IPs: {{ vm_ips }}"

  - name: Ensure new_vms group exists in inventory
    lineinfile:
      path: ./inventory  # the directory of your inventory file.  If else where, adjust path
      line: "[new_vms]"
      create: yes
      insertbefore: BOF
    delegate_to: localhost

  - name: Add VMs to persistent inventory file
    lineinfile:
      path: ./inventory  # the directory of your inventory file.  If else where, adjust path
      line: "{{ item }} ansible_host={{ item }} ansible_user={{ vm_ssh_user }}"
      create: yes
      insertafter: "\\[new_vms\\]"  # Insert AFTER the header for the group
    loop: "{{ vm_ips }}"
    when: vm_ips is defined
    delegate_to: localhost

  - name: Refresh inventory
    meta: refresh_inventory

  - name: Wait for SSH to become available
    wait_for:
      host: "{{ item }}"
      port: 22
      delay: 10
      timeout: 300
    loop: "{{ vm_ips }}"
    when: vm_ips is defined

- name: Configure new VMs
  hosts: new_vms
  gather_facts: yes
  become: yes
  vars_files:
    - ./group_vars/all/vault.yml 
  vars:
    ansible_remote_tmp: "/tmp"

  tasks:
  - name: Import post config play
    ansible.builtin.import_tasks: proxmox_vm_post_config.yml
  
  - name: Completion Message
    ansible.builtin.shell: echo "VM creation completed. Firewalld enabled and JRE21 installed and configured"

    
    